version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - rabbitmq
    env_file:
      - ./producer/.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - rabbitmq
    env_file:
      - ./consumer/.env
    networks:
      - app-network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
