version: "3.9"
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: medicosdb
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 20

  api:
    build: .
    container_name: node.js
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: secret
      DB_NAME: medicosdb
      SYNC: "true"
      LOGGING: "false"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  dbdata:
