version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo-agenda
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  web:
    build: .
    container_name: node-agenda
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/agenda_db
